import type { ProductSeed } from "../product-builder";
import { sizeVariantGroup } from "../product-builder";

export const breadCakeSeeds: ProductSeed[] = [
  {
    slug: "sourdough-classic",
    name: "ซาวร์โดว์คลาสสิก",
    categoryId: "cat-bread",
    shortDescription: "ขนมปังหมักธรรมชาติ 24 ชั่วโมง เปลือกกรอบ เนื้อในนุ่มชุ่ม",
    description:
      "ซาวร์โดว์สูตรดั้งเดิมที่หมักแป้งด้วยยีสต์ธรรมชาตินาน 24 ชั่วโมง ให้รสเปรี้ยวอ่อนๆ กลิ่นหอมเฉพาะตัว เปลือกนอกกรอบ เนื้อในนุ่มชุ่มมีรูอากาศสวยงาม เหมาะทานคู่เนยหรือทำแซนด์วิช",
    ingredients: ["แป้งสาลี", "น้ำ", "เกลือ", "หัวเชื้อยีสต์ธรรมชาติ"],
    storageInstructions: "เก็บในถุงกระดาษที่อุณหภูมิห้อง ทานให้หมดภายใน 3 วัน หรือแช่แข็งได้นาน 1 เดือน",
    shelfLifeDays: 3,
    weightGrams: 500,
    price: 145,
    imageIds: ["photo-1509440159596-0249088772ff", "photo-1586444248902-2f64eddc13df"],
    stockQuantity: 18,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 132,
    daysAgoCreated: 400,
  },
  {
    slug: "whole-wheat-loaf",
    name: "ขนมปังโฮลวีท",
    categoryId: "cat-bread",
    shortDescription: "ขนมปังโฮลวีท 100% ไฟเบอร์สูง เพื่อสุขภาพ",
    description:
      "ทำจากแป้งโฮลวีทแท้ 100% ไม่ใส่น้ำตาลทรายขาวฟอกสี ให้พลังงานที่ดีต่อสุขภาพ เนื้อแน่นแต่ไม่แข็งกระด้าง เหมาะสำหรับมื้อเช้าหรือคนที่ควบคุมอาหาร",
    ingredients: ["แป้งโฮลวีท", "น้ำ", "ยีสต์", "น้ำผึ้ง", "เกลือ", "เมล็ดฟักทอง"],
    storageInstructions: "เก็บในถุงซิปล็อคที่อุณหภูมิห้อง ทานให้หมดภายใน 4 วัน",
    shelfLifeDays: 4,
    weightGrams: 450,
    price: 120,
    imageIds: ["photo-1534620808146-d33bb39128b2"],
    stockQuantity: 12,
    rating: 4.5,
    reviewCount: 58,
    daysAgoCreated: 200,
  },
  {
    slug: "milk-loaf-fluffy",
    name: "ขนมปังนมนุ่ม",
    categoryId: "cat-bread",
    shortDescription: "ขนมปังนมเนื้อฟู หอมกลิ่นนมสด นุ่มละมุนทุกคำ",
    description:
      "ขนมปังนมสไตล์ญี่ปุ่น เนื้อฟูนุ่มเหมือนสำลี หอมกลิ่นนมสดแท้ ไม่ใส่สารกันบูด อบใหม่ทุกวัน เหมาะทานเปล่าๆ หรือทาแยม",
    ingredients: ["แป้งสาลี", "นมสด", "เนยสด", "ไข่ไก่", "น้ำตาล", "ยีสต์"],
    storageInstructions: "เก็บในถุงปิดสนิทที่อุณหภูมิห้อง ทานให้หมดภายใน 2 วัน",
    shelfLifeDays: 2,
    weightGrams: 400,
    price: 95,
    compareAtPrice: 115,
    imageIds: ["photo-1600102186542-82cbd5e7bdb4"],
    stockQuantity: 25,
    isBestSeller: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 210,
    daysAgoCreated: 15,
  },
  {
    slug: "chocolate-fudge-cake",
    name: "ช็อกโกแลตฟัดจ์เค้ก",
    categoryId: "cat-cake",
    shortDescription: "เค้กช็อกโกแลตเข้มข้น ฟัดจ์นุ่มละลายในปาก",
    description:
      "เค้กช็อกโกแลตสูตรเข้มข้นจากโกโก้แท้ 70% ตัดกับครีมฟัดจ์นุ่มเนียน หวานกำลังดีไม่หวานแหลม เหมาะเป็นของขวัญหรือฉลองวันพิเศษ",
    ingredients: ["ดาร์กช็อกโกแลต", "โกโก้ผง", "แป้งเค้ก", "เนยสด", "ไข่ไก่", "น้ำตาล"],
    storageInstructions: "แช่เย็นในตู้เย็น ทานให้หมดภายใน 3 วัน นำออกจากตู้เย็น 15 นาทีก่อนทาน",
    shelfLifeDays: 3,
    weightGrams: 900,
    price: 590,
    compareAtPrice: 650,
    imageIds: ["photo-1578985545062-69928b1d9587", "photo-1606313564200-e75d5e30476c"],
    stockQuantity: 6,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 176,
    variantGroups: [sizeVariantGroup],
    daysAgoCreated: 300,
  },
  {
    slug: "strawberry-shortcake",
    name: "สตรอว์เบอร์รี่ชอร์ตเค้ก",
    categoryId: "cat-cake",
    shortDescription: "เค้กสปันจ์นุ่มสอดไส้ครีมสดและสตรอว์เบอร์รี่สด",
    description:
      "เค้กสไตล์ญี่ปุ่นเนื้อสปันจ์เบานุ่ม ประกบครีมสดรสละมุนและสตรอว์เบอร์รี่สดคัดพิเศษ หวานน้อย หอมนมสด เหมาะทานคู่ชากาแฟยามบ่าย",
    ingredients: ["แป้งเค้ก", "ครีมสด", "สตรอว์เบอร์รี่สด", "ไข่ไก่", "น้ำตาล"],
    storageInstructions: "แช่เย็นในตู้เย็นตลอดเวลา ทานให้หมดภายใน 2 วัน",
    shelfLifeDays: 2,
    weightGrams: 800,
    price: 550,
    imageIds: ["photo-1571115177098-24ec42ed204d"],
    stockQuantity: 8,
    isSeasonal: true,
    rating: 4.7,
    reviewCount: 94,
    variantGroups: [sizeVariantGroup],
    daysAgoCreated: 20,
  },
  {
    slug: "matcha-red-bean-cake",
    name: "มัทฉะเค้กถั่วแดง",
    categoryId: "cat-cake",
    shortDescription: "เค้กมัทฉะเข้มข้นสอดไส้ถั่วแดงกวน หอมมันกลมกล่อม",
    description:
      "เค้กมัทฉะจากผงมัทฉะเกรดพรีเมียมจากอุจิ ผสานความหอมมันของถั่วแดงกวนแบบดั้งเดิม ให้รสขมนิดหวานหน่อยลงตัว เหมาะสำหรับคนรักชาเขียว",
    ingredients: ["ผงมัทฉะ", "แป้งเค้ก", "ถั่วแดงกวน", "ครีมสด", "น้ำตาล"],
    storageInstructions: "แช่เย็นในตู้เย็น ทานให้หมดภายใน 3 วัน",
    shelfLifeDays: 3,
    weightGrams: 850,
    price: 620,
    imageIds: ["photo-1571877227200-a0d98ea607e9"],
    stockQuantity: 5,
    isNew: true,
    rating: 4.6,
    reviewCount: 41,
    variantGroups: [sizeVariantGroup],
    daysAgoCreated: 10,
  },
  {
    slug: "banana-walnut-loaf",
    name: "บานาน่าวอลนัทเค้ก",
    categoryId: "cat-cake",
    shortDescription: "เค้กกล้วยหอมเนื้อแน่น ผสมวอลนัทกรุบกรอบ",
    description:
      "เค้กกล้วยหอมสุกจากกล้วยธรรมชาติ เนื้อเค้กชุ่มฉ่ำหอมกลิ่นกล้วยแท้ๆ ผสมวอลนัทอบกรอบให้สัมผัสหลากหลาย ไม่หวานจัด ทานเป็นมื้อว่างได้สบายๆ",
    ingredients: ["กล้วยหอมสุก", "แป้งสาลี", "วอลนัท", "เนยสด", "น้ำตาลทรายแดง"],
    storageInstructions: "เก็บในกล่องปิดสนิทที่อุณหภูมิห้อง ทานให้หมดภายใน 4 วัน",
    shelfLifeDays: 4,
    weightGrams: 500,
    price: 220,
    imageIds: ["photo-1675712841671-cbcbe2c84103"],
    stockQuantity: 14,
    rating: 4.4,
    reviewCount: 37,
    daysAgoCreated: 150,
  },
  {
    slug: "garlic-cheese-bread",
    name: "ขนมปังกระเทียมชีส",
    categoryId: "cat-bread",
    shortDescription: "ขนมปังนุ่มทาเนยกระเทียมโรยชีสหอมกรุ่น",
    description:
      "ขนมปังเนื้อนุ่มทาด้วยเนยกระเทียมสูตรเข้มข้น โรยหน้าด้วยชีสมอสซาเรลลาละลาย อบร้อนๆ หอมกรุ่นทั้งร้าน เหมาะทานเป็นของว่างหรือคู่ซุป",
    ingredients: ["แป้งสาลี", "เนยสด", "กระเทียม", "ชีสมอสซาเรลลา", "พาร์สลีย์"],
    storageInstructions: "ทานทันทีขณะอุ่นเพื่อรสชาติดีที่สุด หรือแช่เย็นและอุ่นไมโครเวฟก่อนทาน",
    shelfLifeDays: 2,
    weightGrams: 350,
    price: 89,
    imageIds: ["photo-1568254183919-78a4f43a2877"],
    stockQuantity: 20,
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 88,
    daysAgoCreated: 90,
  },
  {
    slug: "taro-coconut-cake",
    name: "เผือกมะพร้าวเค้ก",
    categoryId: "cat-cake",
    shortDescription: "เค้กเผือกหอมมันตัดกับครีมมะพร้าวอ่อน",
    description:
      "เค้กรสไทยที่ผสานความหอมมันของเผือกแท้กับครีมมะพร้าวอ่อนหวานนุ่ม ให้กลิ่นหอมเป็นเอกลักษณ์ ไม่เหมือนใคร เหมาะเป็นของฝากช่วงเทศกาล",
    ingredients: ["เผือก", "มะพร้าวอ่อน", "แป้งเค้ก", "ครีมสด", "น้ำตาลมะพร้าว"],
    storageInstructions: "แช่เย็นในตู้เย็น ทานให้หมดภายใน 3 วัน",
    shelfLifeDays: 3,
    weightGrams: 800,
    price: 480,
    imageIds: ["photo-1621303837174-89787a7d4729"],
    stockQuantity: 0,
    isSeasonal: true,
    rating: 4.3,
    reviewCount: 22,
    variantGroups: [sizeVariantGroup],
    daysAgoCreated: 60,
  },
];
