import type { ProductSeed } from "../product-builder";
import { flavorVariantGroup } from "../product-builder";

export const pastryOtherSeeds: ProductSeed[] = [
  {
    slug: "butter-croissant",
    name: "ครัวซองต์เนยแท้",
    categoryId: "cat-pastry",
    shortDescription: "ครัวซองต์เนยฝรั่งเศสแท้ ชั้นบางกรอบ หอมเนยเข้มข้น",
    description:
      "ครัวซองต์สูตรฝรั่งเศสแท้ ใช้เนยฝรั่งเศสเกรดพรีเมียม พับทบกว่า 27 ชั้น อบจนได้เปลือกกรอบทองสวย เนื้อในนุ่มเป็นชั้นๆ หอมเนยเข้มข้นทุกคำ",
    ingredients: ["แป้งสาลี", "เนยฝรั่งเศส", "ยีสต์", "นม", "น้ำตาล"],
    storageInstructions: "ทานภายในวันที่ซื้อเพื่อความกรอบอร่อยที่สุด อุ่นเตาอบ 5 นาทีก่อนทานได้",
    shelfLifeDays: 1,
    weightGrams: 80,
    price: 65,
    imageIds: ["photo-1555507036-ab1f4038808a", "photo-1555507036-ab1f4038808a"],
    stockQuantity: 30,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 245,
    daysAgoCreated: 500,
  },
  {
    slug: "pain-au-chocolat",
    name: "แพงโอช็อกโกลาต์",
    categoryId: "cat-pastry",
    shortDescription: "เพสตรี้เนยสอดไส้ช็อกโกแลตแท่ง 2 แท่ง หอมกรอบ",
    description:
      "เพสตรี้เนยชั้นบางกรอบสอดไส้ด้วยช็อกโกแลตแท่งคุณภาพดี 2 แท่งต่อชิ้น ให้รสหวานขมกลมกล่อม เนื้อสัมผัสกรอบนอกนุ่มในเหมือนครัวซองต์",
    ingredients: ["แป้งสาลี", "เนยฝรั่งเศส", "ดาร์กช็อกโกแลต", "ยีสต์"],
    storageInstructions: "ทานภายในวันที่ซื้อ หรืออุ่นเตาอบ 5 นาทีก่อนทาน",
    shelfLifeDays: 1,
    weightGrams: 90,
    price: 75,
    imageIds: ["photo-1623334044303-241021148842"],
    stockQuantity: 22,
    isNew: true,
    rating: 4.7,
    reviewCount: 63,
    daysAgoCreated: 25,
  },
  {
    slug: "chocolate-chip-cookie",
    name: "ช็อกโกแลตชิพคุกกี้",
    categoryId: "cat-cookie",
    shortDescription: "คุกกี้เนยสดขอบกรอบตรงกลางนุ่ม ผสมช็อกโกแลตชิพเต็มคำ",
    description:
      "คุกกี้สไตล์อเมริกันเนื้อหนา ขอบกรอบตรงกลางนุ่มเหนียวหนึบ อบด้วยเนยสดแท้และช็อกโกแลตชิพเบลเยียมเกรดพรีเมียม หอมมันทุกคำ",
    ingredients: ["แป้งสาลี", "เนยสด", "ช็อกโกแลตชิพ", "น้ำตาลทรายแดง", "ไข่ไก่"],
    storageInstructions: "เก็บในกล่องมิดชิดที่อุณหภูมิห้อง ทานให้หมดภายใน 7 วัน",
    shelfLifeDays: 7,
    weightGrams: 90,
    price: 55,
    imageIds: ["photo-1499636136210-6f4ee915583e"],
    stockQuantity: 40,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 189,
    daysAgoCreated: 250,
  },
  {
    slug: "matcha-white-choc-cookie",
    name: "คุกกี้มัทฉะไวท์ช็อก",
    categoryId: "cat-cookie",
    shortDescription: "คุกกี้มัทฉะหอมขมตัดกับไวท์ช็อกโกแลตหวานมัน",
    description:
      "คุกกี้เนื้อกรอบร่วนผสมผงมัทฉะแท้ ให้รสขมนิดๆ ตัดกับไวท์ช็อกโกแลตชิ้นโตหวานมัน ลงตัวสำหรับคนชอบชาเขียว",
    ingredients: ["แป้งสาลี", "ผงมัทฉะ", "ไวท์ช็อกโกแลต", "เนยสด", "น้ำตาล"],
    storageInstructions: "เก็บในกล่องมิดชิดที่อุณหภูมิห้อง ทานให้หมดภายใน 7 วัน",
    shelfLifeDays: 7,
    weightGrams: 90,
    price: 60,
    imageIds: ["photo-1499636136210-6f4ee915583e"],
    stockQuantity: 3,
    isNew: true,
    rating: 4.5,
    reviewCount: 29,
    daysAgoCreated: 8,
  },
  {
    slug: "vanilla-buttercream-cupcake",
    name: "คัพเค้กวานิลลาบัตเตอร์ครีม",
    categoryId: "cat-cupcake",
    shortDescription: "คัพเค้กเนื้อนุ่มหอมวานิลลาแท้ บีบหน้าครีมสวยงาม",
    description:
      "คัพเค้กเนื้อฟูนุ่มหอมวานิลลาแท้จากมาดากัสการ์ บีบหน้าด้วยบัตเตอร์ครีมเนื้อเนียนหวานกำลังดี ตกแต่งสวยงามเหมาะเป็นของขวัญหรือปาร์ตี้",
    ingredients: ["แป้งเค้ก", "เนยสด", "วานิลลา", "ไข่ไก่", "น้ำตาลไอซิ่ง"],
    storageInstructions: "แช่เย็นในตู้เย็น ทานให้หมดภายใน 3 วัน นำออกจากตู้เย็น 10 นาทีก่อนทาน",
    shelfLifeDays: 3,
    weightGrams: 100,
    price: 65,
    imageIds: ["photo-1519869325930-281384150729"],
    stockQuantity: 24,
    rating: 4.6,
    reviewCount: 71,
    variantGroups: [flavorVariantGroup(["วานิลลา", "ช็อกโกแลต", "สตรอว์เบอร์รี่"])],
    daysAgoCreated: 100,
  },
  {
    slug: "redvelvet-cupcake",
    name: "เรดเวลเว็ตคัพเค้ก",
    categoryId: "cat-cupcake",
    shortDescription: "คัพเค้กเรดเวลเว็ตสีแดงสวย ครีมชีสหอมมัน",
    description:
      "คัพเค้กสีแดงสวยเนื้อนุ่มละมุน หอมกลิ่นโกโก้อ่อนๆ ตัดกับครีมชีสหน้าเนียนหวานมันกำลังดี เป็นตัวเลือกยอดฮิตสำหรับงานเลี้ยง",
    ingredients: ["แป้งเค้ก", "โกโก้ผง", "ครีมชีส", "สีผสมอาหารธรรมชาติ", "เนยสด"],
    storageInstructions: "แช่เย็นในตู้เย็น ทานให้หมดภายใน 3 วัน",
    shelfLifeDays: 3,
    weightGrams: 100,
    price: 70,
    imageIds: ["photo-1614707267537-b85aaf00c4b7"],
    stockQuantity: 16,
    rating: 4.7,
    reviewCount: 54,
    daysAgoCreated: 180,
  },
  {
    slug: "classic-glazed-donut",
    name: "โดนัทเคลือบน้ำตาลคลาสสิก",
    categoryId: "cat-donut",
    shortDescription: "โดนัทเนื้อนุ่มฟู เคลือบน้ำตาลบางเบาหวานพอดี",
    description:
      "โดนัททอดสดใหม่เนื้อฟูนุ่มเบาสไตล์อเมริกัน เคลือบด้วยน้ำตาลไอซิ่งบางๆ หวานกำลังดีไม่หวานเลี่ยน เป็นเมนูคลาสสิกที่ไม่มีวันเบื่อ",
    ingredients: ["แป้งสาลี", "ยีสต์", "นม", "น้ำตาลไอซิ่ง", "เนยสด"],
    storageInstructions: "ทานภายในวันที่ซื้อเพื่อความนุ่มอร่อยที่สุด",
    shelfLifeDays: 1,
    weightGrams: 70,
    price: 45,
    imageIds: ["photo-1533910534207-90f31029a78e"],
    stockQuantity: 35,
    isBestSeller: true,
    rating: 4.5,
    reviewCount: 112,
    daysAgoCreated: 350,
  },
  {
    slug: "matcha-strawberry-donut",
    name: "โดนัทมัทฉะสตรอว์เบอร์รี่",
    categoryId: "cat-donut",
    shortDescription: "โดนัทสองสีสวย เคลือบมัทฉะและสตรอว์เบอร์รี่",
    description:
      "โดนัทเนื้อนุ่มเคลือบสองหน้าสีสวยงาม ฝั่งมัทฉะหอมขมอ่อนๆ ฝั่งสตรอว์เบอร์รี่หวานเปรี้ยวละมุน ถ่ายรูปสวยและอร่อยครบรส",
    ingredients: ["แป้งสาลี", "ผงมัทฉะ", "ผงสตรอว์เบอร์รี่", "น้ำตาลไอซิ่ง", "เนยสด"],
    storageInstructions: "ทานภายในวันที่ซื้อเพื่อความนุ่มอร่อยที่สุด",
    shelfLifeDays: 1,
    weightGrams: 75,
    price: 55,
    imageIds: ["photo-1533910534207-90f31029a78e"],
    stockQuantity: 4,
    isNew: true,
    isSeasonal: true,
    rating: 4.6,
    reviewCount: 33,
    daysAgoCreated: 5,
  },
];
